spring:
  application:
    name: desafio-devops
  
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/devops}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.uniesp.desafio: DEBUG
