name: Desafio Pipeline Uniesp

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # ETAPA 1: O GUARDIÃO
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # TODO: Configurar o ambiente Go
      
      # TODO: Comando para rodar os testes unitários
      # Dica: O pipeline deve PARAR se o teste falhar.
      
      # TODO: Login e Build/Push da imagem Docker
      # Dica: Use o SHA do commit como tag para garantir imutabilidade.

  # ETAPA 2: HOMOLOGAÇÃO
  staging-stage:
    # ERRO PROPOSITAL: Falta a dependência aqui. 
    # Sem ela, este job rodará ao mesmo tempo que o de cima.
    runs-on: ubuntu-latest
    steps:
      # TODO: Comando para simular a migração do banco de dados
      - name: Migração de Banco
        run: echo "O grupo deve implementar o comando de migração aqui"

      # TODO: Puxar a imagem do registry e "implantar" (echo)

  # ETAPA 3: PRODUÇÃO
  production-stage:
    # TODO: Definir a dependência correta
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Implantando a mesma imagem de Staging..."

      # TODO: Implementar o Smoke Test
      # Dica: Use um comando que verifique o status HTTP de uma rota.
